

export const SET_PLAYER_ID = 'SET_PLAYER_ID';
export const MQTT_CONNECTED = 'MQTT_CONNECTED';
export const MQTT_SUBSCRIBE = 'MQTT_SUBSCRIBE';
export const MQTT_MESSAGE = 'MQTT_MESSAGE';
export const MQTT_CONSUME = 'MQTT_CONSUME';

export const MQTT_DISCONNECTED = 'MQTT_DISCONNECTED';
export const MQTT_UNSUBSCRIBE = 'MQTT_UNSUBSCRIBE';
